import React, { useEffect } from 'react';
import SiteHeader from '@/components/SiteHeader';
import Footer from '../components/Footer';
import { Card, CardContent } from '../components/ui/card';
import { DollarSign, AlertCircle, Mail, ShieldAlert, FileText, HelpCircle } from 'lucide-react';

const Refund: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      <SiteHeader />
      
      <main className="flex-grow pt-24 pb-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            
            {/* Header Section */}
            <div className="text-center mb-12">
              <div className="inline-flex items-center justify-center p-3 bg-red-100 text-red-700 rounded-full mb-6">
                <DollarSign className="w-8 h-8" />
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6">
                Refund Policy
              </h1>
              <p className="text-lg text-slate-600 max-w-2xl mx-auto">
                ADR Wealth Advisors LLC, d/b/a The Score Machine
              </p>
            </div>

            <Card className="shadow-xl border-0 bg-white overflow-hidden">
              <div className="h-2 bg-gradient-to-r from-red-600 to-orange-600"></div>
              <CardContent className="p-8 md:p-12 prose prose-slate max-w-none">
                
                {/* Last Updated Date */}
                <div className="mb-8 p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <p className="text-sm text-slate-500 mb-0">
                    <strong>Effective Date:</strong> {new Date().toLocaleDateString()}
                  </p>
                  <p className="text-sm text-slate-500 mt-2">
                    This Refund Policy governs all fees, charges, and payments related to the use of The Score Machine software platform and associated services (the "Services"). This Policy is part of and incorporated into the SCORE MACHINE MASTER SOFTWARE & SERVICES AGREEMENT (the "Agreement").
                  </p>
                </div>

                <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                  <span className="text-red-600">1.</span> Non-Refundable Nature of All Fees
                </h2>
                <p className="text-slate-600 leading-relaxed">
                  All Subscription Fees, setup fees, usage charges, and any other amounts paid or payable under the Agreement are strictly non-refundable, non-cancelable, and fully earned by the Company upon payment.
                </p>

                <h3 className="text-xl font-semibold text-slate-800 mt-6">1.1 Acknowledgment of Immediate Delivery</h3>
                <p className="text-slate-600 leading-relaxed">
                  The User expressly acknowledges that the Platform constitutes a hosted, on-demand software-as-a-service (SaaS) environment that provides immediate electronic delivery of digital content and proprietary functionality upon the issuance of valid access credentials or activation of the Account. Once access is granted, the Company's obligation to provide the services for the corresponding billing period is deemed fully performed and satisfied.
                </p>

                <h3 className="text-xl font-semibold text-slate-800 mt-6">1.2 No Refunds for Non-Use</h3>
                <p className="text-slate-600 leading-relaxed mb-4">
                  No refund, credit, or offset shall be due or payable for:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600">
                  <li>Partial periods of service use.</li>
                  <li>The User’s failure to utilize the Platform or Services after access has been granted.</li>
                  <li>The suspension or termination of access due to the User's breach of the Agreement.</li>
                  <li>Any claim of dissatisfaction with the analytical results, recommendations, or outcomes generated by the Platform.</li>
                </ul>

                <h3 className="text-xl font-semibold text-slate-800 mt-6">1.3 Effect of Cancellation or Termination</h3>
                <p className="text-slate-600 leading-relaxed">
                  Termination, expiration, or cancellation of the Agreement (whether voluntary or for cause) does not relieve the User of the obligation to pay all fees and charges accrued or payable prior to the effective date of termination. Termination of access does not entitle the User to any refund or credit for unused time or functionality.
                </p>

                <hr className="my-8 border-slate-200" />

                <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                  <span className="text-red-600">2.</span> Chargeback and Payment Reversal Restrictions
                </h2>

                <h3 className="text-xl font-semibold text-slate-800 mt-6">2.1 Prohibition on Chargebacks</h3>
                <p className="text-slate-600 leading-relaxed">
                  The User expressly agrees to resolve any billing disputes directly with the Company in accordance with the Agreement's terms. The User shall not initiate, file, or participate in any credit-card chargeback, ACH reversal, or other payment dispute through a financial institution or payment processor ("Chargebacks").
                </p>
                <div className="bg-orange-50 border-l-4 border-orange-500 p-4 my-4">
                  <p className="text-slate-700 text-sm mb-0">
                    <strong>Exception:</strong> This restriction does not apply in the limited and verifiable circumstance where a transaction was demonstrably unauthorized by the User (e.g., proven identity theft or fraud not involving User negligence).
                  </p>
                </div>

                <h3 className="text-xl font-semibold text-slate-800 mt-6">2.2 Consequences of Improper Chargebacks</h3>
                <p className="text-slate-600 leading-relaxed mb-4">
                  Any attempt by the User to obtain a Chargeback in violation of this Policy shall constitute a material breach of the Agreement and may be treated as intentional fraud. Upon such occurrence, the Company reserves the right to:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600">
                  <li>Immediately suspend or terminate the User's Account.</li>
                  <li>Pursue recovery of the full disputed amount, associated bank/processor fees, administrative costs, and attorneys' fees.</li>
                  <li>Pursue additional remedies, including liquidated damages and reporting the conduct to relevant financial and credit authorities.</li>
                </ul>

                <hr className="my-8 border-slate-200" />

                <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                  <span className="text-red-600">3.</span> Dispute Procedure (For Billing Errors Only)
                </h2>
                <p className="text-slate-600 leading-relaxed mb-4">
                  If the User, in good faith, believes a billing error or clerical mistake has occurred, the User must follow the mandatory dispute procedure:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-slate-600">
                  <li><strong>Notice:</strong> Provide the Company with written notice of the specific dispute within ten (10) calendar days of the charge date.</li>
                  <li><strong>Detail:</strong> The notice must clearly identify the charge, the amount in question, and a detailed statement of the basis for the dispute.</li>
                  <li><strong>Waiver:</strong> Failure to submit a timely written notice of dispute constitutes an irrevocable waiver of the right to contest that charge.</li>
                </ul>
                <div className="bg-blue-50 border-l-4 border-blue-500 p-4 my-4">
                  <p className="text-slate-700 text-sm mb-0">
                    <strong>Please note:</strong> This procedure is for billing errors only and is not a mechanism for seeking a refund for dissatisfaction with the Services.
                  </p>
                </div>

                <hr className="my-8 border-slate-200" />

                <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                  <span className="text-red-600">4.</span> Contact Us
                </h2>
                <p className="text-slate-600 leading-relaxed mb-6">
                  For questions regarding your billing or this Refund Policy, please contact the Company’s billing department in writing:
                </p>
                
                <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
                  <p className="font-bold text-slate-900 mb-1">ADR Wealth Advisors LLC d/b/a The Score Machine</p>
                  <p className="text-slate-600 mb-4">Attn: Legal Department<br/>5830 E 2ND ST, STE 7000 #24151<br/>Casper, Wyoming 82609</p>
                  
                  <div className="flex items-center gap-2 text-slate-600">
                    <Mail className="h-5 w-5 text-red-500" />
                    <a href="mailto:adrwealthadvisorsllc@gmail.com" className="text-red-600 hover:underline font-medium">
                      adrwealthadvisorsllc@gmail.com
                    </a>
                  </div>
                </div>

              </CardContent>
            </Card>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Refund;
