import { useEffect, useState } from 'react';
import { CalendarClock, ExternalLink, Loader2, Plus, Save, Trash2 } from 'lucide-react';
import SuperAdminLayout from '@/components/SuperAdminLayout';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const timezones = ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles', 'Europe/London', 'Asia/Karachi'];
type Data = { settings: any; availability: any[]; blocked_dates: any[]; appointments: any[] };

export default function SuperAdminAppointments() {
  const [data, setData] = useState<Data>({ settings: {}, availability: [], blocked_dates: [], appointments: [] });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [availability, setAvailability] = useState({ day_of_week: 1, start_time: '09:00', end_time: '17:00', active: true });
  const [blocked, setBlocked] = useState({ blocked_date: '', start_time: '', end_time: '', reason: '' });

  const load = async () => {
    setLoading(true);
    try { const response = await api.get('/api/appointments/manage/overview'); setData(response.data.data); setError(''); }
    catch (requestError: any) { setError(requestError?.response?.data?.error || 'Unable to load consultation settings.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);

  const run = async (action: () => Promise<unknown>) => {
    setSaving(true); setError('');
    try { await action(); await load(); }
    catch (requestError: any) { setError(requestError?.response?.data?.error || 'Unable to save changes.'); }
    finally { setSaving(false); }
  };

  if (loading) return <SuperAdminLayout title="Consultations"><div className="flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin" />Loading…</div></SuperAdminLayout>;

  const counts = data.appointments.reduce((result: Record<string, number>, item) => ({ ...result, [item.status]: (result[item.status] || 0) + 1 }), {});
  return <SuperAdminLayout title="Consultation Booking" description="Manage the shared 30-minute consultation calendar, Zoom meetings, and booking history."><div className="space-y-6">
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-4">{[['All', data.appointments.length], ['Confirmed', counts.confirmed || 0], ['Completed', counts.completed || 0], ['Cancelled', counts.cancelled || 0]].map(([label, count]) => <Card key={String(label)}><CardHeader className="pb-3"><CardDescription>{label}</CardDescription><CardTitle className="text-3xl">{count}</CardTitle></CardHeader></Card>)}</div>
    <Tabs defaultValue="appointments"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="appointments">Appointments</TabsTrigger><TabsTrigger value="availability">Meeting Availability</TabsTrigger><TabsTrigger value="blocked">Blocked Dates & Times</TabsTrigger></TabsList>
      <TabsContent value="appointments" className="mt-5"><Card><CardHeader><CardTitle>All appointments</CardTitle><CardDescription>The Zoom host link is restricted to this Super Admin screen.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead><tr className="border-b text-slate-500">{['Name', 'Company', 'Email', 'Source', 'Date / Time', 'Timezone', 'Status', 'Zoom', 'Created'].map((heading) => <th key={heading} className="p-3 font-medium">{heading}</th>)}</tr></thead><tbody>{data.appointments.map((item) => <tr key={item.id} className="border-b align-top"><td className="p-3 font-semibold">{item.name}<div className="mt-1 font-normal text-slate-500">{item.meeting_reason}</div></td><td className="p-3">{item.company_name || '—'}</td><td className="p-3">{item.email}</td><td className="p-3">{item.booking_source === 'admin_dashboard' ? 'Admin Dashboard' : 'Public Website'}</td><td className="p-3">{new Date(item.start_datetime_utc).toLocaleString('en-US', { timeZone: item.timezone, dateStyle: 'medium', timeStyle: 'short' })}<div className="text-xs text-slate-500">30 minutes</div></td><td className="p-3">{item.timezone}</td><td className="p-3"><select className="rounded-md border bg-white px-2 py-1" value={item.status === 'pending_zoom' || item.status === 'zoom_failed' ? item.status : item.status} disabled={['pending_zoom', 'zoom_failed'].includes(item.status) || saving} onChange={(event) => run(() => api.put(`/api/appointments/manage/appointments/${item.id}/status`, { status: event.target.value }))}><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No Show</option>{item.status === 'pending_zoom' && <option value="pending_zoom">Pending Zoom</option>}{item.status === 'zoom_failed' && <option value="zoom_failed">Zoom Failed</option>}</select></td><td className="p-3"><div className="space-y-1">{item.zoom_join_url && <a className="flex items-center gap-1 text-emerald-700 hover:underline" href={item.zoom_join_url} target="_blank" rel="noreferrer">Join <ExternalLink className="h-3 w-3" /></a>}{item.zoom_start_url && <a className="flex items-center gap-1 text-blue-700 hover:underline" href={item.zoom_start_url} target="_blank" rel="noreferrer">Host <ExternalLink className="h-3 w-3" /></a>}</div></td><td className="p-3">{new Date(item.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{data.appointments.length === 0 && <p className="py-10 text-center text-slate-500">No appointments yet.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="availability" className="mt-5 space-y-5"><Card><CardHeader><CardTitle>Central booking settings</CardTitle><CardDescription>Appointment duration is fixed and enforced at 30 minutes.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-4"><div className="space-y-2"><Label>Schedule timezone</Label><select className="h-10 w-full rounded-md border px-3" value={data.settings.timezone} onChange={(e) => setData({ ...data, settings: { ...data.settings, timezone: e.target.value } })}>{timezones.map((zone) => <option key={zone}>{zone}</option>)}</select></div><div className="space-y-2"><Label>Booking window (days)</Label><Input type="number" value={data.settings.booking_window_days} onChange={(e) => setData({ ...data, settings: { ...data.settings, booking_window_days: Number(e.target.value) } })} /></div><div className="space-y-2"><Label>Minimum notice (minutes)</Label><Input type="number" value={data.settings.minimum_notice_minutes} onChange={(e) => setData({ ...data, settings: { ...data.settings, minimum_notice_minutes: Number(e.target.value) } })} /></div><div className="space-y-2"><Label>Duration</Label><Input value="30 minutes (fixed)" disabled /></div><div className="md:col-span-4"><Button disabled={saving} onClick={() => run(() => api.put('/api/appointments/manage/settings', { timezone: data.settings.timezone, booking_window_days: data.settings.booking_window_days, minimum_notice_minutes: data.settings.minimum_notice_minutes, active: Boolean(data.settings.active) }))}><Save className="mr-2 h-4 w-4" />Save Settings</Button></div></CardContent></Card>
        <Card><CardHeader><CardTitle>Weekly availability</CardTitle><CardDescription>Add multiple periods to the same day to create breaks.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-4"><select className="h-10 rounded-md border px-3" value={availability.day_of_week} onChange={(e) => setAvailability({ ...availability, day_of_week: Number(e.target.value) })}>{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><Input type="time" value={availability.start_time} onChange={(e) => setAvailability({ ...availability, start_time: e.target.value })} /><Input type="time" value={availability.end_time} onChange={(e) => setAvailability({ ...availability, end_time: e.target.value })} /><Button disabled={saving} onClick={() => run(() => api.post('/api/appointments/manage/availability', availability))}><Plus className="mr-2 h-4 w-4" />Add Time Range</Button></div><div className="grid gap-3 md:grid-cols-2">{data.availability.map((rule) => <div key={rule.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">{weekdays[rule.day_of_week]}</p><p className="text-sm text-slate-600">{String(rule.start_time).slice(0, 5)} – {String(rule.end_time).slice(0, 5)}</p></div><Button variant="ghost" size="icon" onClick={() => run(() => api.delete(`/api/appointments/manage/availability/${rule.id}`))}><Trash2 className="h-4 w-4 text-red-600" /></Button></div>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="blocked" className="mt-5"><Card><CardHeader><CardTitle>Block a date or part of a day</CardTitle><CardDescription>Leave both times blank to block the entire date.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-5"><Input type="date" value={blocked.blocked_date} onChange={(e) => setBlocked({ ...blocked, blocked_date: e.target.value })} /><Input type="time" value={blocked.start_time} onChange={(e) => setBlocked({ ...blocked, start_time: e.target.value })} /><Input type="time" value={blocked.end_time} onChange={(e) => setBlocked({ ...blocked, end_time: e.target.value })} /><Input placeholder="Reason" value={blocked.reason} onChange={(e) => setBlocked({ ...blocked, reason: e.target.value })} /><Button disabled={saving || !blocked.blocked_date} onClick={() => run(() => api.post('/api/appointments/manage/blocked-dates', { ...blocked, start_time: blocked.start_time || null, end_time: blocked.end_time || null }))}><CalendarClock className="mr-2 h-4 w-4" />Block</Button></div><div className="space-y-3">{data.blocked_dates.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-semibold">{String(item.blocked_date).slice(0, 10)}</p><p className="text-sm text-slate-600">{item.start_time ? `${String(item.start_time).slice(0, 5)} – ${String(item.end_time).slice(0, 5)}` : 'Full day'} · {item.reason || 'Unavailable'}</p></div><Button variant="ghost" size="icon" onClick={() => run(() => api.delete(`/api/appointments/manage/blocked-dates/${item.id}`))}><Trash2 className="h-4 w-4 text-red-600" /></Button></div>)}</div></CardContent></Card></TabsContent>
    </Tabs>
  </div></SuperAdminLayout>;
}
